### ISSUE TITLE
Extracting Multiple CSS Files From the Same Bundle

### ISSUE THREAD

**Issue by daniel-nagy** [danethurber/webpack-manifest-plugin#63] opened 2017-07-22 20:09 UTC
I'm generating two different css files from my app bundle. One file contains app specific styling and the other contains reusable components. The entry for the reusable components is `index.scss` and the app styles are colocated.

My Webpack config can be summarized as follows:

```javascript
const extractAppStyles = new ExtractTextPlugin({
  allChunks: true,
  filename: '[name].[contenthash].css'
});

const extractReusableStyles = new ExtractTextPlugin({
  allChunks: true,
  filename: 'styles.[contenthash].css'
});

const appCssRule = {
  include: APP,
  test: /\.scss$/,
  use: extractAppStyles.extract({...})
};

const reusableCssRule = {
  include: STYLES_ENTRY,
  test: STYLES_ENTRY,
  use: extractReusableStyles.extract({...})
};

module.exports = {
  entry: {
    app: ['index.js', 'index.scss']
  },
  plugins: [
    extractAppStyles,
    extractReusableStyles,
    new ManifestPlugin()
  ]
};
```

Webpack will then generate 2 css files for me

* app.hash.css
* styles.hash.css

However, when I examine the manifest file only one of the css files is included

```json
{
  "app.css": "styles.hash.css",
}
```

This seems like some sort of conflict to me.

```
Manifest Plugin Version: 1.1.2,
Webpack Version: 3.1.0
```

**Comment by mastilver** [comment] 2017-07-24 08:47
duplicate of #30 

Let me know if you think it's a different issue

**Closed by mastilver** 2017-07-24 08:47 UTC

**Comment by daniel-nagy** [comment] 2017-07-24 16:17
That seems like the issue, thanks.
